services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_api:
    build:
      context: ./api_backend
    env_file:
      - ./api_backend/.env
    secrets:
      - db-password
    ports:
      - 8080:80

  tg_client:
    build:
      context: ./telegram_client
    env_file:
      - ./telegram_client/.env


volumes:
 db-data:
secrets:
 db-password:
   file: ./api_backend/db/password.txt
